spring:
  application:
    name: rest-java-spring-course
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_java_spring_course?useTimezone=true&serverTimezone=UTC
    username: root
    password: Bruninho
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

logging:
  level:
    com.github.BrunoFontenele: DEBUG